### ISSUE TITLE
question

### ISSUE THREAD

**Issue by nbecker** [gkhayes/mlrose#16]
I'm curious about mlrose, whether it might be useful for 2 problems.
Problem 1: minimal disc covering problem.  Find the centers for a minimal set of discs of unit radius to cover a given set of points in a plane.  These centers take continuous values.

Problem 2: Find a minimal number of sets to partition a set (of points in a plane) such that the euclidean distance between each of the members within each set is greater than some value.

**Comment by gkhayes** [comment]
If you can express what you are trying to find as a fitness function where your aim is to find the set of parameters that minimize/maximize that function, then mlrose should be able to solve it. The difficult part with respect to the problems that you describe is coming up with that fitness function. However, given that these problems have been around for some time, its possible that someone has written a paper on solving them using some sort of randomized optimization algorithm, which would require them to have defined the fitness function. If I was trying to solve these problems, that's where I'd start looking. 
I hope that helps. 
Genevieve.
