### ISSUE TITLE
Infinite loop in find_sample_order()?

### ISSUE THREAD

**Issue by scribby182** [gkhayes/mlrose#17]
Running mimic with {'pop_size': 50, 'keep_pct': 0.2, 'max_attempts': 10, 'max_iters': 100} for a DiscreteOpt(n, oneMax, max_val=2) problem I randomly get stuck in an infinite loop in find_sample_order().  It isn't consistently happening, but if I do a loop of n=1..50 I keep getting caught somewhere around n=10.  Trying to understand what find_sample_order() should do in order to propose a fix, but not confident yet..

**Comment by scribby182** [comment]
I think it might be due to rounding error in dft in the eval_node_probs() function?  Tracing things back, I seem to get a bad parent list that happens when I get a really really small positive number in a column of dft that otherwise has 0's.  As a quick fix to test, I've rounded dft to 7 decimals locally and it seems to run properly now.  

I don't know if I really understanding everything, but hope this helps track things down.

**Comment by gkhayes** [comment]
Hi @scribby182,
Thanks for pointing out this issue. I believe I have now fixed this problem and the latest mlrose release on PyPi (v1.0.1) incorporates this bug fix.
Regards,
Genevieve.
