### ISSUE TITLE
genetic_alg with size of 1 crashes

### ISSUE THREAD

**Issue by garretfick** [gkhayes/mlrose#20]
It probably isn't very meaningful, but if you have a size of 1 when using the genetic algorithm, then reproduce crashes.

```
fitness = mlrose.OneMax()
problem = mlrose.DiscreteOpt(length = 1, fitness_fn = fitness, maximize = True, max_val = 2)
mlrose.genetic_alg(problem)
```

Then you get a crash :(

**Comment by gkhayes** [comment]
Hi @garretfick ,
Thanks for pointing this out. I have now made changes to the code in the repository to fix this issue. These changes will flow through to the next release of mlrose on PyPi.
Regards,
Genevieve.
