### ISSUE TITLE
Feature Request: Use np functionality where needed, support random seeding

### ISSUE THREAD

**Issue by joel99** [gkhayes/mlrose#22]
Thanks for putting together this resource! 
To support evaluating fitness across an ndarray of examples, some functions should use np functionality - specifically I see regular `sum()` used in one_max fitness evaluation, replace with `np.sum(axis=-1)` or the like. Not sure where else this is relevant.

It'd also be helpful if we could provide `random_seed` to optimization objects and algorithms, for consistent results, would require adding a few `np.random.seed()` lines in the respective functions.

**Comment by gkhayes** [comment]
Hi @joel99 ,
Thanks for the suggestions. I have just added these features and committed them to the repository. They will appear in the next release of mlrose on PyPi.
Regards,
Genevieve.
