### ISSUE TITLE
'max_restarts' should be an option for NeuralNetwork 

### ISSUE THREAD

**Issue by brian-bender** [gkhayes/mlrose#24]
When NeuralNetwork gets initialized with the algorithm "randomized_hill_climbing," that algorithm gets a default max_restart of 0.

**Comment by gkhayes** [comment]
Hi @brian-bender ,
Thanks for pointing that out. I have just added that feature to the code in the repository and it will be included in the next release of mlrose on PyPi.
Regards,
Genevieve.
