### ISSUE TITLE
RHC using wrong get_fitness?

### ISSUE THREAD

**Issue by nibelungvalesti** [gkhayes/mlrose#27]
I think the fitness_curve.append in line 210 of algorithms.py is using the incorrect get_fitness (it's using get_pop_fitness)?
When running an RHC, I get a blank array back for the fitness curve.

**Comment by daivinhtran** [comment]
I have the same problem. I think `random_climb`, `random_hill_climb `, and `simulated_annealing` should use `get_fitness` instead. `genetic_alg` and `mimic` still uses `get_pop_fitness` as implemented.

**Comment by nibelungvalesti** [comment]
random_climb? or hill_climb? I think hill_climb should have implemented it correctly from what I see?
Oh and I also made a pull request so you can check it with that fork. I verified that it works...so far!

**Comment by daivinhtran** [comment]
Yeah, you're right. `hill_climb` had it correct already.

**Comment by daivinhtran** [comment]
Ahh I also made the same PR. 😄 I'll close mine.

**Comment by gkhayes** [comment]
I have just merged @nibelungvalesti 's pull request that fixes this issue, so am closing this.
Thanks to @nibelungvalesti and @daivinhtran for pointing it out.
Regards,
Genevieve.
