### ISSUE TITLE
Bias for hidden layers

### ISSUE THREAD

**Issue by phunehehe** [gkhayes/mlrose#30]
It appears that the neural network in mlrose only adds the bias node to the input layer, but not the hidden layers. This is different from what I've seen elsewhere, for example sklearn.

I have a branch that adds this bias to the hidden layers too, and this works well enough for me. Is this something desirable for mlrose? If so I'll try to fix the tests and submit a PR.
https://github.com/phunehehe/mlrose/tree/bias

**Comment by gkhayes** [comment]
Hi @phunehehe ,
That sounds like a great addition to mlrose. I would love for you to submit a PR with that change.
Regards,
Genevieve.
