### ISSUE TITLE
mlrose suitable for variable lengths discrete variables?

### ISSUE THREAD

**Issue by haimivan** [gkhayes/mlrose#35]
Hi,

I am looking for an alternative to a brute force optimisation approach.

My parameter set is the following. So, my problem is a multi-variate, single-objective problem. It is not related to any machine learning task.

```    
    from sklearn.model_selection import ParameterGrid
    from multiprocessing import Pool

    var1 = 'var1'
    var2 = 'var2'
    abc = [1, 2]
    xyz = list(range(1_00_000))
    pg = [{'variant': [var1],
           'abc': abc,
           'xyz': xyz, },
          {'variant': [var2],
           'abc': abc, }]
    parameterGrid = ParameterGrid(pg)
```
So I have variable lengths of parameters, my parameters can only have discrete values, and  not all parameters do exist dependant from other parameters.

I would like to avoid brute force, as the execution of the cost function is quite time consuming.

Would I be able to use mlrose for my problem? 

(I ask this as `DiscreteOpt` expects fixed lengths for all parameters). 

Thanks in advance!

**Comment by gkhayes** [comment]
Hi @haimivan,

Sorry about taking so long to get back to you. 

As I understand your problem, I don't think you could solve it using mlrose directly. However, you might be able to solve it indirectly by dividing it into multiple sub-problems (i.e. one for each variant), working out the optimal parameter values for each variant, and then working out which variant performs best.

I hope that helps.

Regards,

Genevieve.

**Comment by haimivan** [comment]
@gkhayes ,

Thanks :-)
