### ISSUE TITLE
Hill Climb Curve?

### ISSUE THREAD

**Issue by Kingloko** [gkhayes/mlrose#38]
I was looking at the code and it looks like the curve array only gets updated once per restart, I'd expect it to update once per iteration. 

Is that on purpose or a bug?

Code snippet below for context:

```
for _ in range(restarts + 1):
         ...

        while iters < max_iters:
            ...

       ...
        if curve:
            fitness_curve.append(problem.get_fitness())```

**Comment by gkhayes** [comment]
This is being addressed by #44.
