### ISSUE TITLE
Six Peaks Opt

### ISSUE THREAD

**Issue by davideasaf** [gkhayes/mlrose#41]
Code being referenced: https://github.com/gkhayes/mlrose/blob/71ee20aa9e6dd8d945c9dc1f6d33151511938db3/mlrose/fitness.py#L393-L408

I'm reading through: https://papers.nips.cc/paper/1328-mimic-finding-optima-by-estimating-probability-densities.pdf to understand the implementation of this alg and i'm finding that 6 peaks does not give 4 optima as expected. 

The reason is because the evaluation always uses
`fitness = max(tail_0, head_1) + _r` on line 406

and NOT the `tail` or `head` that actually fulfilled the OR conditional for R(X,T). 

In the image below, I run a four peaks and six peaks fitness function analysis and have circled the peaks that should match with the other max optimum based on what i presume to be the correct logic based on the above paper. 

![image](https://user-images.githubusercontent.com/11589969/66543836-79f4e580-eb04-11e9-9a3a-fd04d3a45242.png)

**Comment by davideasaf** [comment]
If I’m thinking along the right lines, I’d be delighted to make the PR and contribute.

**Comment by gkhayes** [comment]
Hi @davideasaf,
Good pick up. I just did my own checks, with pen and paper, and I agree with you that six peaks doesn't work as expected, as it currently stands. If you make a PR to fix this issue, I will definitely approve it.
Thanks for pointing this out, and I look forward to seeing your PR.
Regards,
Genevieve.

**Comment by gkhayes** [comment]
Resolved through #43.
