### ISSUE TITLE
bug for mutation_probability in genetic algorithms

### ISSUE THREAD

**Issue by hanbrianlee** [gkhayes/mlrose#47]
I believe the inequality sign should be flipped in the following code:
As we want say 10% mutation probability to mean we want 10% of the time mutating children. At 10% with the current code, 90% of children will get mutated.

def mutate(self, child, mutation_probability):
    if np.random.rand() > mutation_probability:
        # do swap mutation
        m1 = np.random.randint(len(child))
        m2 = np.random.randint(len(child))
        tmp = child[m1]
        child[m1] = child[m2]
        child[m2] = tmp
    return child

**Comment by parkds** [comment]
You posted the code from hiive fork, this is the implementation in mlrose:

rand = np.random.uniform(size=self.length)
mutate = np.where(rand < mutation_prob)[0]

**Comment by hanbrianlee** [comment]
you're right, it seems like i made an issue on the wrong page haha

**Comment by hanbrianlee** [comment]
so for those using mlrose-hiive, flip that sign. I'll close this issue
you can find the file in  your site package directory/mlrose_hiive/algorithms/mutators/swap_mutator.py
(i.e. /home/brian/.local/lib/python3.6/site-packages/mlrose_hiive/algorithms/mutators/swap_mutator.py)
